# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  repository:  
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  type: LoadBalancer
  externalPort: 5678
  internalPort: 5678

config:
  existingConfigMapName:

spring:
  application:
    name: sampleservice2-hystrixturbine
  cloud:
    config:
      enabled: false
      uri:

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone:  

global:
  useConfigServerBootstrap: false
  eureka:
    service:
      name:
      port:

