{{- $root := . -}}
{{ $fullname := include "hystrix.fullname" . }}
{{ $name := include "hystrix.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  {{ if .Values.service.name }}
  name: {{ .Values.service.name }}
  {{ else }}
  name: {{ $fullname }}
  {{ end }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.spring.application.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
  selector:
    component: {{ .Values.spring.application.name }}
